/**
 * Generate Express.js router code from a Bazable contract.
 */
export function generateExpress(endpoints, options = {}) {
  const withValidation = options.validation !== false; // default true
  let code = `// Auto-generated by Bazable – Express.js API Router\n`;
  code += `// Generated at ${new Date().toISOString()}\n\n`;

  if (withValidation) {
    code += `import { z } from 'zod';\n`;
  }
  code += `import { Router } from 'express';\n\n`;
  code += `const router = Router();\n\n`;

  // Group endpoints by path
  const pathGroups = {};
  for (const [key, entry] of Object.entries(endpoints)) {
    let url = key;
    let method = 'GET';
    // Handle "METHOD URL" keys
    const methodMatch = key.match(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\s+(.+)$/i);
    if (methodMatch) {
      method = methodMatch[1].toUpperCase();
      url = methodMatch[2];
    }
    // Extract path from full URL
    let routePath = url;
    try {
      const parsed = new URL(url);
      routePath = parsed.pathname;
    } catch {}
    if (!pathGroups[routePath]) pathGroups[routePath] = [];
    pathGroups[routePath].push({ method, entry, originalKey: key });
  }

  for (const [routePath, handlers] of Object.entries(pathGroups)) {
    // Generate a simple function name
    const funcName = routePath
      .replace(/[\/\-]/g, '_')
      .replace(/^_+/, '')
      .replace(/_+$/, '')
      .toLowerCase() || 'root';

    // Request schema (if any)
    const firstHandler = handlers[0];
    const requestSchema = firstHandler?.entry?.request;
    if (withValidation && requestSchema && Object.keys(requestSchema).length > 0) {
      code += `const ${funcName}Schema = z.object({\n`;
      for (const [field, type] of Object.entries(requestSchema)) {
        switch (type) {
          case 'string': code += `  ${field}: z.string(),\n`; break;
          case 'number': code += `  ${field}: z.number(),\n`; break;
          case 'boolean': code += `  ${field}: z.boolean(),\n`; break;
          default: code += `  ${field}: z.any(),\n`; break;
        }
      }
      code += `});\n\n`;
    }

    for (const { method, entry, originalKey } of handlers) {
      const handlerName = `${funcName}_${method.toLowerCase()}`;
      code += `// ${originalKey}\n`;
      code += `router.${method.toLowerCase()}('${routePath}', async (req, res) => {\n`;
      code += `  try {\n`;

      // Mock response based on response schema
      const responseSchema = entry?.response;
      if (responseSchema && Object.keys(responseSchema).length > 0) {
        code += `    // Mock response (replace with real logic)\n`;
        code += `    const data = {\n`;
        for (const [field, type] of Object.entries(responseSchema)) {
          switch (type) {
            case 'string': code += `      ${field}: 'mock_${field}',\n`; break;
            case 'number': code += `      ${field}: 1,\n`; break;
            case 'boolean': code += `      ${field}: true,\n`; break;
            default: code += `      ${field}: null,\n`; break;
          }
        }
        code += `    };\n`;
      } else {
        code += `    const data = { message: '${funcName} handler' };\n`;
      }

      code += `    res.json({ success: true, data });\n`;
      code += `  } catch (error) {\n`;
      code += `    res.status(500).json({ success: false, message: error.message });\n`;
      code += `  }\n`;
      code += `});\n\n`;
    }
  }

  code += `export default router;\n`;
  return code;
}
