export function generateHono(endpoints, options = {}) {
  const withValidation = options.validation !== false;
  let code = `// Auto-generated by Bazable – Hono API Router\n`;
  code += `// Generated at ${new Date().toISOString()}\n\n`;

  if (withValidation) {
    code += `import { zValidator } from '@hono/zod-validator';\n`;
    code += `import { z } from 'zod';\n`;
  }
  code += `import { Hono } from 'hono';\n\n`;
  code += `const app = new Hono();\n\n`;

  const pathGroups = {};
  for (const [key, entry] of Object.entries(endpoints)) {
    let url = key;
    let method = 'GET';
    const methodMatch = key.match(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS|HEAD)\s+(.+)$/i);
    if (methodMatch) {
      method = methodMatch[1].toUpperCase();
      url = methodMatch[2];
    }
    let routePath = url;
    try { const parsed = new URL(url); routePath = parsed.pathname; } catch {}
    if (!pathGroups[routePath]) pathGroups[routePath] = [];
    pathGroups[routePath].push({ method, entry, originalKey: key });
  }

  for (const [routePath, handlers] of Object.entries(pathGroups)) {
    const funcName = routePath.replace(/[\/\-]/g, '_').replace(/^_+/, '').replace(/_+$/, '').toLowerCase() || 'root';
    const firstHandler = handlers[0];
    const requestSchema = firstHandler?.entry?.request;

    if (withValidation && requestSchema && Object.keys(requestSchema).length > 0) {
      code += `const ${funcName}Schema = z.object({\n`;
      for (const [field, type] of Object.entries(requestSchema)) {
        switch (type) {
          case 'string': code += `  ${field}: z.string(),\n`; break;
          case 'number': code += `  ${field}: z.number(),\n`; break;
          case 'boolean': code += `  ${field}: z.boolean(),\n`; break;
          default: code += `  ${field}: z.any(),\n`; break;
        }
      }
      code += `});\n\n`;
    }

    for (const { method, entry, originalKey } of handlers) {
      const handlerName = `${funcName}_${method.toLowerCase()}`;
      code += `// ${originalKey}\n`;
      const methodLower = method.toLowerCase();
      code += `app.${methodLower}('${routePath}', async (c) => {\n`;

      const responseSchema = entry?.response;
      if (responseSchema && Object.keys(responseSchema).length > 0) {
        code += `  const data = {\n`;
        for (const [field, type] of Object.entries(responseSchema)) {
          switch (type) {
            case 'string': code += `    ${field}: 'mock_${field}',\n`; break;
            case 'number': code += `    ${field}: 1,\n`; break;
            case 'boolean': code += `    ${field}: true,\n`; break;
            default: code += `    ${field}: null,\n`; break;
          }
        }
        code += `  };\n`;
      } else {
        code += `  const data = { message: '${funcName} handler' };\n`;
      }

      code += `  return c.json({ success: true, data });\n`;
      code += `});\n\n`;
    }
  }

  code += `export default app;\n`;
  return code;
}
