import { Command } from 'commander';
import fs from 'fs/promises';
import path from 'path';
import { readConfig, validateProjectContext } from '../utils/config.js';
import { logger } from '../utils/logger.js';
import { mapToTsType, sanitizePropertyName, generateFunctionName } from '../utils/schema.js';

const client = new Command('client')
  .description('Generate a strictly‑typed API client (bazableClient.ts)')
  .option('-o, --output <dir>')
  .option('--stdout')
  .option('--prefix <prefix>', '', '')
  .action(async (options) => {
    await validateProjectContext();

    const config = await readConfig();
    if (!config || Object.keys(config.endpoints || {}).length === 0) {
      logger.error('No endpoints in the contract.');
      process.exit(1);
    }

    const endpoints = Object.entries(config.endpoints)
      .filter(([url, entry]) => entry.request || entry.response || !('schema_status' in entry && Object.keys(entry).length <= 2))
      .map(([url, entry]) => ({
        url,
        entry,
        hasRequest: entry.request && Object.keys(entry.request).length > 0,
        hasResponse: entry.response && Object.keys(entry.response).length > 0,
      }));

    if (endpoints.length === 0) {
      logger.warn('No schemas found. Use "bazable add" or define request/response schemas.');
      return;
    }

    let code = '// Auto-generated by Bazable\n\n';
    code += '// Base URL: ' + (config.baseUrl || 'N/A') + '\n\n';

    for (const { url, entry, hasRequest, hasResponse } of endpoints) {
      const funcName = options.prefix + generateFunctionName(url);
      const reqTypeName = funcName + 'Request';
      const respTypeName = funcName + 'Response';

      if (hasRequest) {
        code += `interface ${reqTypeName} {\n`;
        for (const [key, type] of Object.entries(entry.request)) {
          code += `  ${sanitizePropertyName(key)}: ${mapToTsType(type)};\n`;
        }
        code += '}\n\n';
      }

      if (hasResponse) {
        code += `interface ${respTypeName} {\n`;
        for (const [key, type] of Object.entries(entry.response)) {
          code += `  ${sanitizePropertyName(key)}: ${mapToTsType(type)};\n`;
        }
        code += '}\n\n';
      }

      const params = hasRequest ? `data: ${reqTypeName}` : '';
      const returnType = hasResponse ? `Promise<${respTypeName}>` : 'Promise<any>';
      const fetchBody = hasRequest ? ', { method: \'POST\', body: JSON.stringify(data) }' : '';

      code += `export async function ${funcName}(${params}): ${returnType} {\n`;
      code += `  const response = await fetch('${url}'${fetchBody});\n`;
      code += `  if (!response.ok) throw new Error(\`HTTP \${response.status}\`);\n`;
      code += `  return response.json();\n`;
      code += '}\n\n';
    }

    if (options.stdout) {
      console.log(code);
      return;
    }

    const outDir = options.output || process.cwd();
    await fs.mkdir(outDir, { recursive: true }).catch(() => {});
    const filePath = path.join(outDir, 'bazableClient.ts');
    await fs.writeFile(filePath, code, 'utf-8');
    logger.success(`Generated client → ${filePath}`);
  });

export default client;
