import { Command } from 'commander';
import fs from 'fs/promises';
import path from 'path';
import { readConfig, validateProjectContext } from '../utils/config.js';
import { logger } from '../utils/logger.js';

const docs = new Command('docs')
  .description('Generate static API documentation HTML')
  .option('-o, --output <dir>', 'Output directory', './bazable-docs')
  .action(async (options) => {
    await validateProjectContext();

    const config = await readConfig();
    if (!config || Object.keys(config.endpoints || {}).length === 0) {
      logger.error('No endpoints in the contract.');
      process.exit(1);
    }

    const outDir = path.resolve(process.cwd(), options.output);
    await fs.mkdir(outDir, { recursive: true });

    const endpointCards = Object.entries(config.endpoints).map(([url, entry]) => {
      const method = entry.method || 'GET';
      const requestSchema = entry.request ? JSON.stringify(entry.request, null, 2) : 'None';
      const responseSchema = entry.response ? JSON.stringify(entry.response, null, 2) : 'None';
      return `
        <div style="border:1px solid #ddd;margin:10px 0;padding:15px;border-radius:5px;">
          <h3><span style="background:#eee;padding:2px 8px;border-radius:3px;">${method}</span> ${url}</h3>
          <h4>Request Schema:</h4>
          <pre>${requestSchema}</pre>
          <h4>Response Schema:</h4>
          <pre>${responseSchema}</pre>
        </div>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html>
<head><title>API Documentation - ${config.projectName || 'Bazable'}</title></head>
<body style="font-family:sans-serif;max-width:900px;margin:0 auto;padding:20px;">
  <h1>API Documentation</h1>
  <p>Project: ${config.projectName || 'unknown'} | Base URL: ${config.baseUrl || 'not set'}</p>
  ${endpointCards}
  <p><small>Generated by Bazable</small></p>
</body>
</html>`;

    const filePath = path.join(outDir, 'index.html');
    await fs.writeFile(filePath, html, 'utf-8');
    logger.success(`Documentation generated → ${filePath}`);
  });

export default docs;
