import { Command } from 'commander';
import fs from 'fs/promises';
import path from 'path';
import { readConfig, validateProjectContext } from '../utils/config.js';
import { logger } from '../utils/logger.js';
import { mapToTsType, sanitizePropertyName, generateInterfaceName } from '../utils/schema.js';

const types = new Command('types')
  .description('Generate TypeScript interfaces from contracted API schemas')
  .option('-o, --output <dir>', 'Output directory')
  .option('-c, --stdout')
  .option('--prefix <prefix>', '', '')
  .option('--name <name>')
  .action(async (options) => {
    await validateProjectContext();

    const config = await readConfig();
    if (!config || Object.keys(config.endpoints || {}).length === 0) {
      logger.error('No endpoints in the contract.');
      process.exit(1);
    }

    const schemas = Object.entries(config.endpoints)
      .filter(([url, entry]) => entry && !('schema_status' in entry && Object.keys(entry).length <= 2))
      .map(([url, schema]) => ({ url, schema }));

    if (schemas.length === 0) {
      logger.warn('No full schemas found. Use "bazable add <url>" to fetch schemas first.');
      return;
    }

    let output = '// Auto-generated by Bazable\n\n';

    for (const { url, schema } of schemas) {
      let interfaceName;
      if (options.name && schemas.length === 1) {
        interfaceName = (options.prefix || '') + options.name;
      } else {
        interfaceName = generateInterfaceName(url, options.prefix);
      }

      const props = Object.entries(schema)
        .map(([key, type]) => `  ${sanitizePropertyName(key)}: ${mapToTsType(type)};`)
        .join('\n');

      output += `export interface ${interfaceName} {\n${props}\n}\n\n`;
    }

    if (options.stdout) {
      console.log(output);
      return;
    }

    const outDir = options.output || process.cwd();
    await fs.mkdir(outDir, { recursive: true }).catch(() => {});
    const filePath = path.join(outDir, 'bazable-types.ts');
    await fs.writeFile(filePath, output, 'utf-8');
    logger.success(`Generated ${schemas.length} interface(s) → ${filePath}`);
  });

export default types;
